site_name: Walter P. Reuther Library SuperManual

theme:
    name: material
    features: navigation.footer

markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.snippets:
        base_path: docs/snippets
    - pymdownx.superfences
    - sane_lists
    - toc:
        permalink: true

nav:
    - Section 1 - Accessioning:
        - a. Overview: 01_accessioning/01_01_overview.md
        - b. ArchivesSpace Accessions: 01_accessioning/01_02_archivesspace_accessions.md
        - c. Born-Digital Transfer: 01_accessioning/01_03_born-digital_transfer.md
    - Section 2 -  Arrangement and Description:
        - a. General: 02_arrangement/02_01_general.md
        - b. Special Formats: 02_arrangement/02_02_special-formats.md
        - c. Resources / Collection Level: 02_arrangement/02_03_resources.md
        - d. Archival Objects / Inventories: 02_arrangement/02_04_archival_objects.md
    - Section 3 - Shared Guidelines:
        - a. Extent Calculations: 03_shared/03_01_extent_calculations.md
        - b. ArchivesSpace Events: 03_shared/03_02_events.md
        - c. Agents and Subjects: 03_shared/03_03_agents_subjects.md
        - d. Note Guidelines: 03_shared/03_04_notes.md
        - e. Instances (Containers and Digital Objects): 03_shared/03_05_instances.md
        - f. ArchivesSpace Reports: 03_shared/03_06_reports.md
    - Section 4 - Digitization: 04_digitization.md
    - Section 5 - Access: 05_access.md
    - Contributing: contributing.md
