site_name: Walter P. Reuther Library SuperManual

theme:
    name: material

markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.superfences
    - sane_lists
    - toc:
        permalink: true

nav:
    - Section 1 - Accessioning: 01_accessioning.md
    - Section 2 -  Arrangement and Description:
        - General: 02_arrangement/02_01_general.md
        - Special Formats: 02_arrangement/02_02_special-formats.md
        - ArchivesSpace: 02_arrangement/02_03_archivesspace.md
    - Section 3 - Digitization: 03_digitization.md
    - Section 4 - Access: 04_access.md
    - Section 5 - Contributing: 05_contributing.md
